services:
  web:
    image: pratikbhumkar/toyrobot-ts
    build:
      context: .
      dockerfile: Dockerfile
      target: development-env
    labels:
      name: "A TypeScript variant of Pratik Bhumkar's toyrobot"
    stdin_open: true
    tty: true